/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package shiftsystemprototype;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;

/**
 *
 * @author x12483858
 */
public class ShiftGUI extends javax.swing.JFrame {
    ArrayList<String> employees = new ArrayList<String> ();

    /**
     * Creates new form ShiftGUI
     */
    public ShiftGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        empTF = new javax.swing.JTextField();
        empLbl = new javax.swing.JLabel();
        addBTN = new javax.swing.JButton();
        removeBTN = new javax.swing.JButton();
        rosterBTN = new javax.swing.JButton();
        dispPane = new javax.swing.JScrollPane();
        listTA = new javax.swing.JTextArea();
        clockInBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Shift System");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 20, 140, 29);

        empTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empTFActionPerformed(evt);
            }
        });
        getContentPane().add(empTF);
        empTF.setBounds(60, 90, 186, 20);

        empLbl.setText("Employee Name:");
        getContentPane().add(empLbl);
        empLbl.setBounds(120, 60, 80, 14);

        addBTN.setText("Clock IN");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });
        getContentPane().add(addBTN);
        addBTN.setBounds(30, 130, 100, 23);

        removeBTN.setText("Clock OUT");
        removeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBTNActionPerformed(evt);
            }
        });
        getContentPane().add(removeBTN);
        removeBTN.setBounds(210, 130, 90, 23);

        rosterBTN.setText("Roster");
        getContentPane().add(rosterBTN);
        rosterBTN.setBounds(120, 210, 90, 23);

        listTA.setColumns(20);
        listTA.setRows(5);
        listTA.setBorder(null);
        dispPane.setViewportView(listTA);

        getContentPane().add(dispPane);
        dispPane.setBounds(10, 242, 291, 105);

        clockInBTN.setText("Who has clocked IN?");
        clockInBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clockInBTNActionPerformed(evt);
            }
        });
        getContentPane().add(clockInBTN);
        clockInBTN.setBounds(90, 170, 150, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empTFActionPerformed

    private void clockInBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clockInBTNActionPerformed
        // TODO add your handling code here:
        displayList();
        Collections.sort(employees);
    }//GEN-LAST:event_clockInBTNActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
       
        
        // TODO add your handling code here:
        String tmpName = empTF.getText();
        employees.add(tmpName);
        
        
    }//GEN-LAST:event_addBTNActionPerformed

    private void removeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBTNActionPerformed
        
        
        
        
        //set String for name to be stored to from the employee textfield
        String tmpName = empTF.getText();
        
        
        
        
        //remove the value the text fields input was stored to from the array
        employees.remove(tmpName);
        
        
        
        
        //refresh the list
        displayList();
        
        
        
        
    }//GEN-LAST:event_removeBTNActionPerformed

    private void displayList() {
        Iterator iter;
        iter =  employees.iterator();
        String newList = "";
        while (iter.hasNext())
        {  
                newList = newList + iter.next() + "\n";
        }
        listTA.setText(newList);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShiftGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShiftGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShiftGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShiftGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShiftGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JButton clockInBTN;
    private javax.swing.JScrollPane dispPane;
    private javax.swing.JLabel empLbl;
    private javax.swing.JTextField empTF;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextArea listTA;
    private javax.swing.JButton removeBTN;
    private javax.swing.JButton rosterBTN;
    // End of variables declaration//GEN-END:variables
}
